### ISSUE TITLE
Looking forward to the official code.

### ISSUE THREAD

**Issue by Dean-UQ** [gongda0e/FUTR#1]
Hi,
    I am one of the readers of your paper FUTR and I would like to know when its codes will be available?
Many thanks.

**Comment by gongda0e** [comment]
Hello, 
Thank you for being so interested in our paper!
We will release the code until July.

**Comment by rashidch** [comment]
Hi, 
I read your paper on FUTR and I would like to ask **what would be the action query input to the decoder when decoding in a parallel manner at inference time?**

**Comment by gongda0e** [comment]
@rashidch Hello, we use the learned action query at inference time, which is already trained in the training stage.

**Comment by rashidch** [comment]
Thanks for the answer. Kindly release the code of the paper as it can help others to further explore the topic.

**Comment by hongsong-wang** [comment]
Hello, Dayoung, the code has not released yet.

**Comment by gongda0e** [comment]
The code is updated. Sorry for the late update!
