### ISSUE TITLE
Downloading data

### ISSUE THREAD

**Issue by olga-zats** [gongda0e/FUTR#4]
Hi! Thanks a lot for providing the code!
I encountered a problem with downloading the data from the cloud. The server allows to download only up to 5 GB of data and then requires to wait at least 6 hours. Would it be possible for you to upload it to another cloud, where the download is not restricted? Thank you for your answer in advance!

**Comment by Prism-hua** [comment]
Can you tell me how you solved that problem, I am facing the same!!
@olga-zats
